#+TITLE: 我的书单
#+INCLUDE: "exportopt.org"

* 算法
** 算法导论/Introduction to Algorithms
算法导论/Introduction to Algoriothms是知名的计算机算法教材, 通常被简称为CLRS,
这是四位作者的首字母. 这四位作者分别是[[http://www.cs.dartmouth.edu/~thc/][Thomas H. Cormen]], [[https://people.csail.mit.edu/cel/][Charles E. Leiserson]],
[[http://www.columbia.edu/~cs2035/][Clifford Stein]], [[http://people.csail.mit.edu/rivest/][Ronald Rivest]]. Cormen就职于[[file:university.org::#dartmouth][达特茅斯学院]]([[http://home.dartmouth.edu/][学校主页]]), Stein是
哥伦比亚大学[[http://ieor.columbia.edu/][IEOR]]和[[http://www.cs.columbia.edu/][计算机科学]]的教授. Leiserson与Rivest是[[http://web.mit.edu/][麻省理工]]的教授.

本书是基础算法领域最权威、最详细的著作之一. 很多国际知名大学用本书作为计算机
算法课的教材. 很多论文将其列入参考文献中.

算法导论是一本接近1300页的大部头(英文版, 中文版800多页), 读起来比较艰辛.
[[https://www.zhihu.com/search?type=content&q=%25E7%25AE%2597%25E6%25B3%2595%25E5%25AF%25BC%25E8%25AE%25BA][知乎搜索]]有大量本书内容和学习方法的研讨. 可以在[[http://open.163.com/special/opencourse/algorithms.html][新浪公开课]]或[[https://www.youtube.com/watch?v=HtSuA80QTyo&list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb][youtube]]上查看MIT
算法导论公开课. 我从2011年开始, 投入了大量业余时间在本书研读上. 我在
[[https://github.com/yygcode/ycc][Github Repo ycc]]上有本书诸多算法的实现. 我的[[file:notes-books.org::#introduction-to-algorithms][读书笔记]]有部分习题的解答.

** 算法基础:打开算法之门/Algorithms Unlocked
算法基础作者[[http://www.cs.dartmouth.edu/~thc/][Thomas H. Cormen]], 是算法导论作者之一. 本书只有220页. 包含算法分析,
排序与搜索, 图与最短路径, 字符串操作, 加密, 数据压缩内容.

** 计算机程序设计艺术/The Art of Computer Programming
业界称为[[http://www-cs-faculty.stanford.edu/~knuth/taocp.html][TAOCP]], 作者[[http://www-cs-faculty.stanford.edu/~uno/][Donald E.Knuth(高德纳)]], [[https://www.stanford.edu/][斯坦福]]大学荣誉教授, 1974年图灵奖
得主, 计算机科学先驱人物, 创造了算法分析领域, 在计算机科学及数学领域发表了
多部具有广泛影响的论文和著作. 高德纳最为人知的事迹是撰写了《计算机程序设计
艺术》系列图书, 以及发明的电子排版系统[[https://tug.org/][TeX]](后扩展有[[https://www.latex-project.org/][Latex]]/[[https://tug.org/xetex/][XeTex]]).

计算机程序设计艺术系列计划完成7卷:
- 卷1:基本算法 ::
讲解基本概念和信息结构. 基本概念包括数学准备, MIX汇编和若干
程序设计技术. 信息结构包括线性表(栈, 队列, 链表, 数组), 树(二叉树, 树的基本
数学性质), 多链结构和动态存储分配. 动态存储分配中讲到最先匹配方法和伙伴系统,
在Linux的内存管理模块[[https://www.kernel.org/doc/gorman/html/understand/understand022.html][Boot Memory Allocator]]和[[https://www.kernel.org/doc/gorman/html/understand/understand009.html][Buddy System]]中用到.

- 卷2:半数值算法 ::
讲解随机数与算术. 随机数包括生成均匀随机数的线性同余法,
统计检验, 随机量和随机序列. 算术部分包括浮点, 多精度, 进制转换, 有理数, 多项式,
幂级数等算术. 卷二充斥着复杂的数学运算与分析.

- 卷3:排序与查找 ::
排序部分包含组合性质, 内部排序(插入/交换/选择/合并/分布),最优排序(比较次数最少的
排序/合并/选择), 外部排序(多路合并, 多阶段合并, 级联合并, 反向读取磁带,
震荡排序, 外部基础排序, 双磁带排序, 磁盘与磁鼓). 查找部分包括顺序查找, 键值比较
查找(有序表, 二叉树, 平衡树, 多路树), 数字查找, 散列,辅助键查找. 卷三中的大多
算法在操作系统和应用程序中有着广泛应用, 例如进程VMA(虚拟内存区间段)使用[[https://lwn.net/Articles/184495/][RBTree]],
文件系统中用到的[[https://lwn.net/Articles/490501/][B+树(多路树)]].

- 卷4:组合算法 ::
讲解组合查找与递归. 第4卷涉及范围很大, 分为4A, 4B, 4C三卷出版. 4A讲组合查找,
4B和4C还未发布.

- 卷5:语法算法 :: 讲解词法分析与语法分析. 未发布.
- 卷6:语言理论 :: 未发布.
- 卷7:编译器 :: 未发布.

希望能有闲暇时间, 可细细把玩此套书籍.

** 算法分析导论/An Introduction to the Analysis of Algorithms
算法分析导论(第二版)作者[[https://www.cs.princeton.edu/~rs/][Robert Sedgewick]], [[http://algo.inria.fr/flajolet/][Philippe Flajoet]]. Robert在[[https://www.princeton.edu/][普林斯顿大学]]
计算机科学系就职, 他同时还是多本计算机算法书籍(Algorithms 4th, Algorithms in
Java, Algorithms in C++, Algorithms in C)作者. Philippe于2011年3月22日逝世.

** 算法设计与分析基础/Introduction to The Design and Analysis of Algorithms
算法设计与分析基础, 作者[[http://www.csc.villanova.edu/~levitin/][Anany Levitin]], Villanova大学教授. 包括算法基本概念描述,
效率分析基础, 蛮力法, 减治法, 分治法, 变治法, 时空权衡, 动态规划, 贪婪技术, 迭代
改进, 算法能力极限与超越算法能力极限, 提供了问题求解的诸多一般性策略.

** 算法(第四版)/Algorithms(4th edition)
Java算法的入门书籍. 虽购买诸多时日, 却没有仔细翻阅这本书.

* Linux内核
** 深入理解LINUX内核/Understanding the Linux Kernel
深入理解LINUX内核(第三版), 作者[[http://bovet.sprg.uniroma2.it/][Daniel P.Bovet]]与[[http://cesati.sprg.uniroma2.it/][Marco Cesati]], 翻译陈莉君, 张琼声,
张宏伟. 包含内存寻址, 进程, 中断与异常, 内核同步, 定时测量, 进程调度, 内存管理,
进程地址空间, 系统调用, 信号, 虚拟文件系统, I/O体系结构和设备驱动程序, 块设备
驱动程序, 页高速缓存, 访问文件, 回收页框, Ext2与Ext3文件系统, 进程通信, 程序的
执行诸多章节.

如果只推荐三本LINUX内核编程必读书籍, 我推荐《深入理解LINUX内核》,《深入LINUX内核
架构》,《LINUX设备驱动程序》.

2008年购得此书已接近10年, 偶有翻阅还是心有所得.

** LINUX设备驱动程序/Linux Device Drivers
LINUX设备驱动程序(第三版), 作者Jonathan Corbet, Alessandro Rubini,
Greg Kroah-Hartman. 讲解内核模块加载卸载, 构造和运行, 字符设备驱动程序, 调试
技术, 并发和竞态, 高级字符驱动程序操作, 时间、延迟及延缓操作, 分配内存, 与硬件
通信, 中断处理, 内核的数据结构, PCI驱动程序, USB驱动程序, LINUX设备模型, 内存
映射和DMA, 块设备驱动程序, 网络驱动程序, TTY驱动程序.

2008年购得此书, 当时缺少适当的技术背景, 读此书颇有收获, 并通过此书快速上手模块
开发调试. 在研读深入LINUX内核架构一书, 并多年已处理过PCIe驱动, NIC驱动, I2C驱动
后, 偶有翻阅已是不再有困惑.

** 深入LINUX内核架构/Professional Linux Kernel Architecture
深入LINUX内核架构, 作者[[https://hps.hs-regensburg.de/maw39987/#/home][Wolfgang Mauerer]]. 从简介开始, 到进程管理和调度, 内存管理,
进程虚拟内存, 锁与进程间通信, 设备驱动程序, 模块, 虚拟文件系统, Ext文件系统族,
无持久存储的文件系统, 扩展性和访问控制列表, 网络, 系统调用, 内核活动, 页缓存和
块缓存, 数据同步, 页面回收和页交换, 审计, 再到附录体系结构, C语言注记, 系统启动,
ELF二进制格式, 内核开发过程, 每一个章节, 都收获颇丰.

2012年5月购得此书, 已逾5年. 业余花费小半年完整的啃了一遍, LINUX内核终于不再神秘.

** 深入理解Linux\reg{}虚拟内存管理/Understanding the Linux\reg{} Virtual Memory Manager

- 近期阅读清单。
