#+Title: Emacs安装

* Windows系统下安装Emacs
** 版本选择
从[[https://ftp.gnu.org/gnu/emacs/windows/][这里]]下载稳定的Emacs, 也可以从[[https://alpha.gnu.org/gnu/emacs/pretest/windows/][这里]]下载最新的Emacs. 对于一般用户而言,
emacs-$VERSION-x86_64.zip是最合适的. 除去这个版本, 官方也提供其他no-deps, i686,
w64版本. 此外, 还有[[https://sourceforge.net/projects/ntemacs/][NTEmacs]], 但我没使用过.

下载zip压缩包, 解压缩到目标位置, 在合适位置创建runemacs.exe链接, 我一般配合
[[https://autohotkey.com/][autohotkey]]用用快捷方式\(Ctrl+Win+E\)启动.

** 字体安装
我的[[https://github.com/yygcode/.emacs.d][Emacs配置]]中, Orgmode使用[[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]]字体. 在Win7下安装该字体方法如下:
1. 下载[[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]]. 不使用git下载ZIP压缩包并解压缩;
2. 安装Adobe提供的[[http://www.adobe.com/devnet/opentype/afdko.html][AFDKO字体开发套件]], 下载Win版本, 根据解压缩文件夹下
   FDK/Read_Me_First.html方式操作;
#+BEGIN_QUOTE
After downloading and decompressing the FDK, the only installation step is to add the directory for the FDK programs to your system's environment variable "PATH". This variable contains a list of directory paths, as a single string of text with the directory paths separated by semicolons. When the system needs to find a program that you have typed in a command-line, it looks for that program in all the directories listed in the PATH variable. You need to add the path to the executable FDK directory at '<path to FDK>\Tools\win' to this list. Fortunately, the FDK comes with a command file to do this for you. In order to run this file successfuly, your account does need system admin privileges.

Download the AFDKO archive file and decompress it.
You should now have a folder named "FDK". Move it wherever you want (example: C:\Program Files (x86)\FDK).
Open the "FDK" folder. and find the file "FinishInstallWindows.cmd".
Open a command prompt window. If you do not know how to do this, read the file "FDK\Technical Documentation\CommandLineHowTo.pdf".
Note! The command window must be run with Administrator privileges. If you open a regular command line window, the script will fail. To open a command window with Adminstrator priviliges, right click on the command program icon, and choose "Run with Adminstrator privileges."
Enter the path to the script file in the command window. An easy way to do this is to:
Click once on the file "FinishInstallWindows.cmd". This will place the path to the parent directory at the top of the Explorer window.
Copy the directory path from the top of the Explorer window by selecting the text and copying it. Paste it into the command window (right click, and choose the option "Paste"). Finish the command-line by typing the name of the script file, "FinishInstallWindows.cmd" at the end of the directory path, and then press "RETURN/ENTER".
If all went well the FDK should now be ready to run. To test it, do the following:

Open a Command Prompt window. (Start Menu > Run... > cmd.exe)
Type "autohint -h" (no quotes) and hit "Return". This should give you the Help information about the Autohint tool.
NOTE: If you move the FDK directory to a new location, you will need to change the PATH variable as well.
#+END_QUOTE
上述操作概要描述:
- 拷贝FDK到软件安装目录, 假定为 C:\Program Files (x86)\FDK;
- 以管理员权限打开Cmd, 进入FDK目录, 执行FinishInstallWindows.cmd;
- 系统环境变量增量 C:\Program Files (x86)\FDK\Tools\win;
- 注销或重启系统, 再次登录;
3. 进入Source Code Pro目录, 执行build.cmd;
4. Win7打开控制面板->外观和个性化->字体, 把target目录下OTF/TTF下字体文件拖动到控制面板字体窗口安装.
5. Win10右键字体文件, 选择导入

