#+Title: Emacs FAQ

* 使用问题记录
** 无法加载一个package, 但无法正常安装 20171114
- 错误码提示如下: Error (use-package): monokai-theme :init: Undefined Custom theme monokai
- 根因: 目前还不明确根因
- 解决措施: 在~/.emacs.d/elpa目录下查找对应包(比如: ~/.emacs.d/elpa/monokai-theme-*), 部分
  文件可能异常为空(size等于0).

** EMMS在Windows中文操作系统下无法播放中文名称多媒体 20171119
- 错误提示: No next track in playlist
- 根因: Windows中文默认编码为GBK, Emacs配置设置默认为Emacs导致
- 解决措施: 继续保持默认编码为UTF-8, 设置进程交互编码系统转换
#+BEGIN_SRC emacs-lisp
  (when (string-equal current-language-environment "Chinese-GBK")
    (setq default-process-coding-system '(utf-8-unix . chinese-gbk-dos)))
#+END_SRC
- 更多:
  + 查看Emacs帮助\(C-h v current-language-environment\)和
    \(C-h f prefer-coding-system\), 及Emacs Manual [[https://www.gnu.org/software/emacs/manual/html_node/emacs/International.html#International][International]]和
    [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Non_002dASCII-Characters.html#Non_002dASCII-Characters][Non-ASCII Characters]]了解更多.
  + Windows下载[[https://www.mpg123.de/download/win64][mpg123 win64]], [[https://sourceforge.net/projects/mplayerwin/][mplayer]]
** Emacs退出时提示"Active process exist; kill them and exit anyway" 20171119
- 根因: 默认配置打开了确认, 调整配置即可
- 解决措施: 修改不再提示process未退出(Emacs退出时自动退出)
#+BEGIN_SRC emacs-lisp
  (setq confirm-kill-processes nil)
#+END_SRC

** TODO EMMS在Windows下无法调整音量, amixer找不到
** DONE Windows
- 错误提示1:
Warning (initialization): An error occurred while loading ‘e:/.emacs.d/init.el’:

error: Package ‘use-package-’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
- 解决方法1: 重启emacs

- 错误提示2:
Warning (initialization): An error occurred while loading ‘e:/.emacs.d/init.el’:

File is missing: Cannot open load file, No such file or directory, ggtags

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
- 解决方法2: 重启emacs

** DONE Windows下动态库加载路径设置
+- 部分库(比如gnutls)在启动时需要设置正确, 因此不能在配置文件中(或者最早位置可否?尝试下.)+
- GnuTls and LibXml2 must be enable to find the relevant DLLs during startup.
  failure to do so is not an error, but GnuTls or libxml2 feature won't be
  available to the running session.
- If set environment PATH correctly(e.g., include e:\\msys2\\mingw64\\bin and
  e:\\msys2\\usr\\bin), GnuTls would work correctly but libxml2 still not work.
  The libxml2 only method is to copy dlls(libiconv-2.dll, liblzma-5.dll,
  libxml2-2.dll, zlib1.dll) to emacs.exe/runemacs.exe directory.
- variable: exec-path, load-path, dynamic-library-alist, process-environment
- function: setenv/getenv

http://ftp.uni-bayreuth.de/packages/editors/emacs/windows/
http://gregorygrubbs.com/emacs/10-tips-emacs-windows/
https://stackoverflow.com/questions/771756/what-is-the-difference-between-cygwin-and-mingw

* 常用功能
|------------------------------+------------------+--------------------------|
| Function                     | Key              | Describe                 |
| /                            | <>               | <>                       |
|------------------------------+------------------+--------------------------|
| find-function                | C-c C-f          | 查看函数定义             |
| what-cursor-position         | C-x = / C-u C-x= | 查看光标处的字符(集)信息 |
| list-coding-system           |                  | 查看可用的字符集         |
| describe-language-enviroment |                  |                          |
|------------------------------+------------------+--------------------------|
