#+TITLE: Test Page

[[mailto:yygcode@gmail.com][mail]]

* Disqus
#+BEGIN_VERSE
The SFENCE (Store Fence) instruction controls write ordering by creating a fence
for memory store operations. This instruction guarantees that the result of
every store instruction that precedes the store fence in program order is
globally visible before any store instruction that follows the fence. The SFENCE
instruction provides an efficient way of ensuring ordering between procedures
that produce weakly-ordered data and procedures that consume that data.
#+END_VERSE


#+BEGIN_EXPORT ascii
The SFENCE (Store Fence) instruction controls write ordering by creating a fence
for memory store operations. This instruction guarantees that the result of
every store instruction that precedes the store fence in program order is
globally visible before any store instruction that follows the fence. The SFENCE
instruction provides an efficient way of ensuring ordering between procedures
that produce weakly-ordered data and procedures that consume that data.
#+END_EXPORT

#+BEGIN_CENTER
#+BEGIN_QUOTE
The SFENCE (Store Fence) instruction controls write ordering by creating a fence
for memory store operations. This instruction guarantees that the result of
every store instruction that precedes the store fence in program order is
globally visible before any store instruction that follows the fence. The SFENCE
instruction provides an efficient way of ensuring ordering between procedures
that produce weakly-ordered data and procedures that consume that data.
#+END_QUOTE
#+END_CENTER

#+BEGIN_EXAMPLE
The SFENCE (Store Fence) instruction controls write ordering by creating a fence
for memory store operations. This instruction guarantees that the result of
every store instruction that precedes the store fence in program order is
globally visible before any store instruction that follows the fence. The SFENCE
instruction provides an efficient way of ensuring ordering between procedures
that produce weakly-ordered data and procedures that consume that data.
#+END_EXAMPLE
