#+TITLE: OS安装与基本配置
#+AUTHOR: yanyg
#+EMAIL: yygcode@gmail.com

* TODO Windows
  :PROPERTIES:
  :CUSTOM_ID: win
  :END:
** 安装Windows 7/10
新的设备一般不再提供CD/DVD驱动器, 而只有USB接口. [[https://www.microsoft.com/zh-cn/download/windows-usb-dvd-download-tool][Windows USB DVD Download Tool]]是
微软提供的USB安装盘制作工具. USB盘分区复杂或异常可能导致引导失败. 最简单可靠的
分区是只保留一个分区, 格式化为NTFS. 如果想用一个大容量USB制作随身USB盘, 请参考
[[#usb-stick][随身USB盘]].

Win7/Win10在安装时会自动生成一个小的隐藏分区, 存放引导文件. 对分区无特殊规划的
用户, 这不会有问题. 如果要控制分区方式, 需安装前完成分区, 此时Win7/Win10把引导
分区内容放置到系统分区内(C盘). 定制分区参见[[#partition][Partition]].

Win单系统安装十分简单. 制作USB安装盘, (可选的)准备分区, 接入USB盘开机, 配置BIOS
或使用F12(部分硬件可能是F9~F12的其他键), 用USB引导安装.

Win/Linux双系统参考[[#partition][Partition]]分区. 先安装Win系统, 完成后安装Linux系统, 设置GRUB
引导两个系统. 参见[[#debian-install][Debian Install]].

** 配置Win10
*** 禁止Win+g弹出游戏录制工具栏提示
- Autohotkey配置 =Win+g= google搜索剪贴板内容，不希望弹出提示栏；
- 配置方法：开始->设置->游戏->关掉“使用游戏栏记录游戏剪辑、屏幕截图和广播”。

* TODO Linux
  :PROPERTIES:
  :CUSTOM_ID: linux
  :END:
** TODO Debian
   :PROPERTIES:
   :CUSTOM_ID: linux-debian
   :END:
*** 安装
    :PROPERTIES:
    :CUSTOM_ID: debian-install
    :END:

使用[[https://unetbootin.github.io/][unetbootin]]制作USB安装盘, U盘引导安装.

使用Win/Linux双系统配置的, 执行~update-grub~更新配置文件, 手动修改=defaults=
设置默认操作系统.

*** 配置
**** Apt-Source配置
配置 =/etc/apt/sources.list=:
#+BEGIN_SRC conf
  deb http://httpredir.debian.org/debian jessie main contrib non-free
  #deb http://ftp.us.debian.org/debian/dists/jessie jessie main contrib
  deb-src http://httpredir.debian.org/debian jessie main contrib non-free

  deb http://httpredir.debian.org/debian jessie-updates main contrib non-free
  deb-src http://httpredir.debian.org/debian jessie-updates main contrib non-free

  deb http://security.debian.org/ jessie/updates main contrib non-free
  deb-src http://security.debian.org/ jessie/updates main contrib non-free
#+END_SRC
执行更新和安装:
#+BEGIN_SRC shell
  ~$ sudo apt-get update
  ~$ sudo apt-get install vim
#+END_SRC

**** Thinkpad Trackpoint(小红点)配置
[[https://wiki.debian.org/InstallingDebianOn/Thinkpad/Trackpoint][Debian WIKI]]中配置介绍, 不同Debian配置方式有差异. 示例如下:
#+BEGIN_SRC shell
  ~$ uname -a
  Linux t400 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
  ~$ su
  ~# cat > /usr/share/X11/xorg.conf.d/20-thinkpad.conf.1 <<EOF
  >  Section "InputClass"
  >      Identifier "Trackpoint Wheel Emulation"
  >      MatchProduct       "TPPS/2 IBM TrackPoint|DualPoint Stick|Synaptics Inc. Composite TouchPad / TrackPoint|ThinkPad USB Keyboard with TrackPoint|ThinkPad Compact USB Keyboard with TrackPoint|USB Trackpoint pointing device"
  >      MatchDevicePath    "/dev/input/event*"
  >      Option             "EmulateWheel"          "true"
  >      Option             "EmulateWheelButton"    "2"
  >      Option             "Emulate3Buttons"       "false"
  >      Option             "XAxisMapping"          "6 7"
  >      Option             "YAxisMapping"          "4 5"
  >  EndSection
  > EOF

  # comment: save all your X11 work and exit, then restart X11
  ~# /etc/init.d/gdm3 restart
#+END_SRC
[[https://wiki.archlinux.org/index.php/TrackPoint][ArchLinux]]和[[http://thinkwiki.org/wiki/How_to_configure_the_TrackPoint][thinkwiki]]也有介绍. 单击真心不好用. :)

** TODO LFS

* TODO Partition
  :PROPERTIES:
  :CUSTOM_ID: partition
  :END:

* TODO 随身USB盘
  :PROPERTIES:
  :CUSTOM_ID: usb-stick
  :END:

随身携带一个大容量USB(32G/64G), 包含完整可引导的操作系统, 以及Debian, Redhat,
CentOS, Win 7, Win 10操作系统的安装包, 在特定环境下直接运行USB系统工作, 或者
解决系统引导异常. 这在开发底层系统, 或对系统做深度定制时是常见的.

** 工作原理
用[[https://www.gnu.org/software/grub/][GRUB]]和[[https://sourceforge.net/projects/grub4dos/][grub4dos]]提供多系统引导, 安装Linux到USB盘, 或用[[http://www.linuxfromscratch.org/][LFS]]制作自己的系统.

** 制作方式
*** 分区
使用fdisk分区. part1用做grub, part2用做live linux, part3用做Linux安装系统, part4
是扩展分区, part5/6分别用做win安装盘和win下数据盘. 各分区大小根据USB和安装盘
大小进行随意调整. 如下是64GB USB示例:
#+BEGIN_SRC shell
  yanyg@t:~$ sudo fdisk -l /dev/sdc

  Disk /dev/sdc: 57.9 GiB, 62109253632 bytes, 121307136 sectors
  Units: sectors of 1 * 512 = 512 bytes
  Sector size (logical/physical): 512 bytes / 512 bytes
  I/O size (minimum/optimal): 512 bytes / 512 bytes
  Disklabel type: dos
  Disk identifier: 0xcad4ebea

  Device     Boot     Start       End  Sectors  Size Id Type
  /dev/sdc1            2048  33556479 33554432   16G 83 Linux
  /dev/sdc2        33556480  75499519 41943040   20G 83 Linux
  /dev/sdc3        75499520  88082431 12582912    6G 83 Linux
  /dev/sdc4        88082432 121307135 33224704 15.9G  5 Extended
  /dev/sdc5        88084480 100667391 12582912    6G  7 HPFS/NTFS/exFAT
  /dev/sdc6       100669440 121307135 20637696  9.9G  7 HPFS/NTFS/exFAT
#+END_SRC
