#+TITLE: Screencast Software/录屏软件

-----
* 功能介绍                                                        :screencast:screen capture:
录屏软件(screencast or screen capture)用来录制计算机屏幕输出, 一般也会包含音频
输出或麦克输入. 完整的名词解释参见[[https://en.wikipedia.org/wiki/Screencast][WIKI]]. 录屏在技术分享和在线教领域有广泛使用.

本文介绍Windows/Linux两个系统下开源/自由的优秀录屏软件.

* Windows平台
** Sharex
**** 介绍
ShareX是自由/开源软件, 基于.NET开发, 只能运行在Windows系统上. 支持截屏/录屏, 并
进行各种各样的分享. 界面支持多语言. [[https://en.wikipedia.org/wiki/ShareX][WIKI]]和[[https://zhuanlan.zhihu.com/p/19627720][知乎]]有介绍.
- 代码: [[https://github.com/ShareX/ShareX][github]]
- 主页: https://getsharex.com/
- 下载: [[https://getsharex.com/downloads/][Downloads]]
**** 配置
在[[https://getsharex.com/][主页]]上可找到完整的介绍文档. 录屏配置主菜单位于:
- 英文界面: Task settings->Capture->Screen recorder->Screen recorder options
- 中文界面: 任务设置->截图->屏幕记录->屏幕录制选项

录屏使用[[https://www.ffmpeg.org/][ffmpeg]]实现, 菜单"录屏配置->FFmpeg路径"下点击...设置或下载FFmpeg. 默认
配置未包含音频, 在录屏配置菜单'音频源'中选择麦克风或适当的音频源.

默认热键=Shift+PrtSc=启动/停止录屏, 启动时拖曳鼠标修改录屏区域. 点击菜单
"截图文件夹..."查看历史截图和录屏文件. 热键和录屏文件夹均可在主界面下找到配置
菜单.
**** 我的配置:
- FFmpeg路径: %MyDocuments%\ShareX\Tools\ffmpeg.exe
- 录屏路径: G:\screencast
- 截图路径: G:\screenshot
**** DONE Q&A
- 设置录屏路径和截图路径无效
  关闭ShareX界面时, ShareX依然在后台运行. 在任务栏右键ShareX图标, 选择"退出",
  然后再次启动.
- 什么是GDI Grab
  录屏选项中, 视频源可以选择"GDI Grab". GDI Grab是Windows系统下基于GDI的录屏设备.
  参考[[https://www.ffmpeg.org/ffmpeg-devices.html#gdigrab][FFmpeg GDI Grab]].
